#include "conv_malloc.cuh"
#include "global_avg.cuh"
#include "add_malloc.cuh"
#include "gemm.cuh"

#define INPUTSHAPE 3 * 244 * 244
#define OUTPUTSHAPE 1000
#define TESTNUM 10
#define ITERNUM 500
#define DEBUG false
double inputArr[TESTNUM][INPUTSHAPE];
double benchOutArr[TESTNUM][OUTPUTSHAPE];

double* Conv_0_W;
double* Conv_0_B;
double* Conv_2_W;
double* Conv_2_B;
double* Conv_4_W;
double* Conv_4_B;
double* Conv_5_W;
double* Conv_5_B;
double* Conv_7_W;
double* Conv_7_B;
double* Conv_9_W;
double* Conv_9_B;
double* Conv_10_W;
double* Conv_10_B;
double* Conv_12_W;
double* Conv_12_B;
double* Conv_14_W;
double* Conv_14_B;
double* Conv_16_W;
double* Conv_16_B;
double* Conv_18_W;
double* Conv_18_B;
double* Conv_20_W;
double* Conv_20_B;
double* Conv_21_W;
double* Conv_21_B;
double* Conv_23_W;
double* Conv_23_B;
double* Conv_25_W;
double* Conv_25_B;
double* Conv_27_W;
double* Conv_27_B;
double* Conv_29_W;
double* Conv_29_B;
double* Conv_31_W;
double* Conv_31_B;
double* Conv_33_W;
double* Conv_33_B;
double* Conv_35_W;
double* Conv_35_B;
double* Conv_37_W;
double* Conv_37_B;
double* Conv_38_W;
double* Conv_38_B;
double* Conv_40_W;
double* Conv_40_B;
double* Conv_42_W;
double* Conv_42_B;
double* Conv_44_W;
double* Conv_44_B;
double* Conv_46_W;
double* Conv_46_B;
double* Conv_48_W;
double* Conv_48_B;
double* Conv_50_W;
double* Conv_50_B;
double* Conv_52_W;
double* Conv_52_B;
double* Conv_54_W;
double* Conv_54_B;
double* Conv_56_W;
double* Conv_56_B;
double* Conv_58_W;
double* Conv_58_B;
double* Conv_60_W;
double* Conv_60_B;
double* Conv_61_W;
double* Conv_61_B;
double* Conv_63_W;
double* Conv_63_B;
double* Conv_65_W;
double* Conv_65_B;
double* Conv_67_W;
double* Conv_67_B;
double* Conv_69_W;
double* Conv_69_B;
double* Conv_71_W;
double* Conv_71_B;
double* Conv_73_W;
double* Conv_73_B;
double* Conv_75_W;
double* Conv_75_B;
double* Conv_77_W;
double* Conv_77_B;
double* Conv_78_W;
double* Conv_78_B;
double* Conv_80_W;
double* Conv_80_B;
double* Conv_82_W;
double* Conv_82_B;
double* Conv_84_W;
double* Conv_84_B;
double* Conv_86_W;
double* Conv_86_B;
double* Conv_88_W;
double* Conv_88_B;
double* Conv_90_W;
double* Conv_90_B;
double* Conv_92_W;
double* Conv_92_B;
double* Conv_94_W;
double* Conv_94_B;
double* Conv_95_W;
double* Conv_95_B;
double* Gemm_W;
double* Gemm_B;
double* temp_h;
double* temp_d;

double* Conv_0_out;
double* Conv_2_out;
double* Conv_4_out;
double* Conv_5_out;
double* Conv_7_out;
double* Conv_9_out;
double* Conv_10_out;
double* Conv_12_out;
double* Conv_14_out;
double* Conv_16_out;
double* Conv_18_out;
double* Conv_20_out;
double* Conv_21_out;
double* Conv_23_out;
double* Conv_25_out;
double* Conv_27_out;
double* Conv_29_out;
double* Conv_31_out;
double* Conv_33_out;
double* Conv_35_out;
double* Conv_37_out;
double* Conv_38_out;
double* Conv_40_out;
double* Conv_42_out;
double* Conv_44_out;
double* Conv_46_out;
double* Conv_48_out;
double* Conv_50_out;
double* Conv_52_out;
double* Conv_54_out;
double* Conv_56_out;
double* Conv_58_out;
double* Conv_60_out;
double* Conv_61_out;
double* Conv_63_out;
double* Conv_65_out;
double* Conv_67_out;
double* Conv_69_out;
double* Conv_71_out;
double* Conv_73_out;
double* Conv_75_out;
double* Conv_77_out;
double* Conv_78_out;
double* Conv_80_out;
double* Conv_82_out;
double* Conv_84_out;
double* Conv_86_out;
double* Conv_88_out;
double* Conv_90_out;
double* Conv_92_out;
double* Conv_94_out;
double* Conv_95_out;
double* Avgpool_out;
double* Gemm_out;

void readInput(char *filename)
{
    FILE *fp = NULL;
    fp = fopen(filename, "r");
    for (int i = 0; i < TESTNUM; i++)
        for (int j = 0; j < INPUTSHAPE; j++)
            fscanf(fp, "%lf", &inputArr[i][j]);
}

void readOutput(char *filename)
{
    FILE *fp = NULL;
    fp = fopen(filename, "r");
    for (int i = 0; i < TESTNUM; i++)
        for (int j = 0; j < OUTPUTSHAPE; j++)
            fscanf(fp, "%lf", &benchOutArr[i][j]);
}

void checkOutput(double *out1, double *out2)
{
    double maxDiff = 0;
    for (int i = 0; i < OUTPUTSHAPE; i++)
    {
        maxDiff = (fabs(out1[i] - out2[i]) > maxDiff) ? fabs(out1[i] - out2[i]) : maxDiff;
    }
    if (maxDiff > 1e-5)
    {
        printf("Output dismatch. MaxDiff is %.7f\n", maxDiff);
    }
}

double* imgcpy(double* image_g, int size)
{
    double* residual_g = NULL;
    // cudaMalloc((void**)&residual_g,sizeof(double)*size);
    // cudaMemcpy(residual_g, image_g, sizeof(double)*size, cudaMemcpyDeviceToDevice);
    residual_g = image_g;
    return residual_g;
}

void cudaMallocWithPadding(double** img_p, int channel, int shape, int padding=0)
{
    shape+=padding;
    cudaMalloc(img_p, sizeof(double)*channel*shape*shape*2);
}

void initModel()
{
    FILE *fp = NULL;
    fp = fopen("./params.txt", "r");
    temp_h = new double[32*3*3*3];
    for(int i=0;i<32*3*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32*3*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32*3*3*3, cudaMemcpyHostToDevice);
    Conv_0_W = temp_d;
    delete [] temp_h;
    temp_h = new double[32];
    for(int i=0;i<32;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32, cudaMemcpyHostToDevice);
    Conv_0_B = temp_d;
    delete(temp_h);
    temp_h = new double[32*1*3*3];
    for(int i=0;i<32*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32*1*3*3, cudaMemcpyHostToDevice);
    Conv_2_W = temp_d;
    delete(temp_h);
    temp_h = new double[32];
    for(int i=0;i<32;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32, cudaMemcpyHostToDevice);
    Conv_2_B = temp_d;
    delete(temp_h);
    temp_h = new double[16*32*1*1];
    for(int i=0;i<16*32*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*16*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*16*32*1*1, cudaMemcpyHostToDevice);
    Conv_4_W = temp_d;
    delete(temp_h);
    temp_h = new double[16];
    for(int i=0;i<16;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*16);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*16, cudaMemcpyHostToDevice);
    Conv_4_B = temp_d;
    delete(temp_h);
    temp_h = new double[96*16*1*1];
    for(int i=0;i<96*16*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96*16*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96*16*1*1, cudaMemcpyHostToDevice);
    Conv_5_W = temp_d;
    delete(temp_h);
    temp_h = new double[96];
    for(int i=0;i<96;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96, cudaMemcpyHostToDevice);
    Conv_5_B = temp_d;
    delete(temp_h);
    temp_h = new double[96*1*3*3];
    for(int i=0;i<96*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96*1*3*3, cudaMemcpyHostToDevice);
    Conv_7_W = temp_d;
    delete(temp_h);
    temp_h = new double[96];
    for(int i=0;i<96;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96, cudaMemcpyHostToDevice);
    Conv_7_B = temp_d;
    delete(temp_h);
    temp_h = new double[24*96*1*1];
    for(int i=0;i<24*96*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*24*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*24*96*1*1, cudaMemcpyHostToDevice);
    Conv_9_W = temp_d;
    delete(temp_h);
    temp_h = new double[24];
    for(int i=0;i<24;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*24);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*24, cudaMemcpyHostToDevice);
    Conv_9_B = temp_d;
    delete(temp_h);
    temp_h = new double[144*24*1*1];
    for(int i=0;i<144*24*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144*24*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144*24*1*1, cudaMemcpyHostToDevice);
    Conv_10_W = temp_d;
    delete(temp_h);
    temp_h = new double[144];
    for(int i=0;i<144;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144, cudaMemcpyHostToDevice);
    Conv_10_B = temp_d;
    delete(temp_h);
    temp_h = new double[144*1*3*3];
    for(int i=0;i<144*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144*1*3*3, cudaMemcpyHostToDevice);
    Conv_12_W = temp_d;
    delete(temp_h);
    temp_h = new double[144];
    for(int i=0;i<144;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144, cudaMemcpyHostToDevice);
    Conv_12_B = temp_d;
    delete(temp_h);
    temp_h = new double[24*144*1*1];
    for(int i=0;i<24*144*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*24*144*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*24*144*1*1, cudaMemcpyHostToDevice);
    Conv_14_W = temp_d;
    delete(temp_h);
    temp_h = new double[24];
    for(int i=0;i<24;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*24);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*24, cudaMemcpyHostToDevice);
    Conv_14_B = temp_d;
    delete(temp_h);
    temp_h = new double[144*24*1*1];
    for(int i=0;i<144*24*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144*24*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144*24*1*1, cudaMemcpyHostToDevice);
    Conv_16_W = temp_d;
    delete(temp_h);
    temp_h = new double[144];
    for(int i=0;i<144;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144, cudaMemcpyHostToDevice);
    Conv_16_B = temp_d;
    delete(temp_h);
    temp_h = new double[144*1*3*3];
    for(int i=0;i<144*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144*1*3*3, cudaMemcpyHostToDevice);
    Conv_18_W = temp_d;
    delete(temp_h);
    temp_h = new double[144];
    for(int i=0;i<144;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*144, cudaMemcpyHostToDevice);
    Conv_18_B = temp_d;
    delete(temp_h);
    temp_h = new double[32*144*1*1];
    for(int i=0;i<32*144*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32*144*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32*144*1*1, cudaMemcpyHostToDevice);
    Conv_20_W = temp_d;
    delete(temp_h);
    temp_h = new double[32];
    for(int i=0;i<32;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32, cudaMemcpyHostToDevice);
    Conv_20_B = temp_d;
    delete(temp_h);
    temp_h = new double[192*32*1*1];
    for(int i=0;i<192*32*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192*32*1*1, cudaMemcpyHostToDevice);
    Conv_21_W = temp_d;
    delete(temp_h);
    temp_h = new double[192];
    for(int i=0;i<192;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192, cudaMemcpyHostToDevice);
    Conv_21_B = temp_d;
    delete(temp_h);
    temp_h = new double[192*1*3*3];
    for(int i=0;i<192*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192*1*3*3, cudaMemcpyHostToDevice);
    Conv_23_W = temp_d;
    delete(temp_h);
    temp_h = new double[192];
    for(int i=0;i<192;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192, cudaMemcpyHostToDevice);
    Conv_23_B = temp_d;
    delete(temp_h);
    temp_h = new double[32*192*1*1];
    for(int i=0;i<32*192*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32*192*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32*192*1*1, cudaMemcpyHostToDevice);
    Conv_25_W = temp_d;
    delete(temp_h);
    temp_h = new double[32];
    for(int i=0;i<32;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32, cudaMemcpyHostToDevice);
    Conv_25_B = temp_d;
    delete(temp_h);
    temp_h = new double[192*32*1*1];
    for(int i=0;i<192*32*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192*32*1*1, cudaMemcpyHostToDevice);
    Conv_27_W = temp_d;
    delete(temp_h);
    temp_h = new double[192];
    for(int i=0;i<192;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192, cudaMemcpyHostToDevice);
    Conv_27_B = temp_d;
    delete(temp_h);
    temp_h = new double[192*1*3*3];
    for(int i=0;i<192*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192*1*3*3, cudaMemcpyHostToDevice);
    Conv_29_W = temp_d;
    delete(temp_h);
    temp_h = new double[192];
    for(int i=0;i<192;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192, cudaMemcpyHostToDevice);
    Conv_29_B = temp_d;
    delete(temp_h);
    temp_h = new double[32*192*1*1];
    for(int i=0;i<32*192*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32*192*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32*192*1*1, cudaMemcpyHostToDevice);
    Conv_31_W = temp_d;
    delete(temp_h);
    temp_h = new double[32];
    for(int i=0;i<32;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*32, cudaMemcpyHostToDevice);
    Conv_31_B = temp_d;
    delete(temp_h);
    temp_h = new double[192*32*1*1];
    for(int i=0;i<192*32*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192*32*1*1, cudaMemcpyHostToDevice);
    Conv_33_W = temp_d;
    delete(temp_h);
    temp_h = new double[192];
    for(int i=0;i<192;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192, cudaMemcpyHostToDevice);
    Conv_33_B = temp_d;
    delete(temp_h);
    temp_h = new double[192*1*3*3];
    for(int i=0;i<192*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192*1*3*3, cudaMemcpyHostToDevice);
    Conv_35_W = temp_d;
    delete(temp_h);
    temp_h = new double[192];
    for(int i=0;i<192;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*192, cudaMemcpyHostToDevice);
    Conv_35_B = temp_d;
    delete(temp_h);
    temp_h = new double[64*192*1*1];
    for(int i=0;i<64*192*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64*192*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64*192*1*1, cudaMemcpyHostToDevice);
    Conv_37_W = temp_d;
    delete(temp_h);
    temp_h = new double[64];
    for(int i=0;i<64;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64, cudaMemcpyHostToDevice);
    Conv_37_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_38_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_38_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_40_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_40_B = temp_d;
    delete(temp_h);
    temp_h = new double[64*384*1*1];
    for(int i=0;i<64*384*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64*384*1*1, cudaMemcpyHostToDevice);
    Conv_42_W = temp_d;
    delete(temp_h);
    temp_h = new double[64];
    for(int i=0;i<64;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64, cudaMemcpyHostToDevice);
    Conv_42_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_44_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_44_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_46_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_46_B = temp_d;
    delete(temp_h);
    temp_h = new double[64*384*1*1];
    for(int i=0;i<64*384*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64*384*1*1, cudaMemcpyHostToDevice);
    Conv_48_W = temp_d;
    delete(temp_h);
    temp_h = new double[64];
    for(int i=0;i<64;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64, cudaMemcpyHostToDevice);
    Conv_48_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_50_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_50_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_52_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_52_B = temp_d;
    delete(temp_h);
    temp_h = new double[64*384*1*1];
    for(int i=0;i<64*384*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64*384*1*1, cudaMemcpyHostToDevice);
    Conv_54_W = temp_d;
    delete(temp_h);
    temp_h = new double[64];
    for(int i=0;i<64;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*64, cudaMemcpyHostToDevice);
    Conv_54_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_56_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_56_B = temp_d;
    delete(temp_h);
    temp_h = new double[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_58_W = temp_d;
    delete(temp_h);
    temp_h = new double[384];
    for(int i=0;i<384;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*384, cudaMemcpyHostToDevice);
    Conv_58_B = temp_d;
    delete(temp_h);
    temp_h = new double[96*384*1*1];
    for(int i=0;i<96*384*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96*384*1*1, cudaMemcpyHostToDevice);
    Conv_60_W = temp_d;
    delete(temp_h);
    temp_h = new double[96];
    for(int i=0;i<96;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96, cudaMemcpyHostToDevice);
    Conv_60_B = temp_d;
    delete(temp_h);
    temp_h = new double[576*96*1*1];
    for(int i=0;i<576*96*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576*96*1*1, cudaMemcpyHostToDevice);
    Conv_61_W = temp_d;
    delete(temp_h);
    temp_h = new double[576];
    for(int i=0;i<576;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576, cudaMemcpyHostToDevice);
    Conv_61_B = temp_d;
    delete(temp_h);
    temp_h = new double[576*1*3*3];
    for(int i=0;i<576*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576*1*3*3, cudaMemcpyHostToDevice);
    Conv_63_W = temp_d;
    delete(temp_h);
    temp_h = new double[576];
    for(int i=0;i<576;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576, cudaMemcpyHostToDevice);
    Conv_63_B = temp_d;
    delete(temp_h);
    temp_h = new double[96*576*1*1];
    for(int i=0;i<96*576*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96*576*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96*576*1*1, cudaMemcpyHostToDevice);
    Conv_65_W = temp_d;
    delete(temp_h);
    temp_h = new double[96];
    for(int i=0;i<96;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96, cudaMemcpyHostToDevice);
    Conv_65_B = temp_d;
    delete(temp_h);
    temp_h = new double[576*96*1*1];
    for(int i=0;i<576*96*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576*96*1*1, cudaMemcpyHostToDevice);
    Conv_67_W = temp_d;
    delete(temp_h);
    temp_h = new double[576];
    for(int i=0;i<576;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576, cudaMemcpyHostToDevice);
    Conv_67_B = temp_d;
    delete(temp_h);
    temp_h = new double[576*1*3*3];
    for(int i=0;i<576*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576*1*3*3, cudaMemcpyHostToDevice);
    Conv_69_W = temp_d;
    delete(temp_h);
    temp_h = new double[576];
    for(int i=0;i<576;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576, cudaMemcpyHostToDevice);
    Conv_69_B = temp_d;
    delete(temp_h);
    temp_h = new double[96*576*1*1];
    for(int i=0;i<96*576*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96*576*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96*576*1*1, cudaMemcpyHostToDevice);
    Conv_71_W = temp_d;
    delete(temp_h);
    temp_h = new double[96];
    for(int i=0;i<96;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*96, cudaMemcpyHostToDevice);
    Conv_71_B = temp_d;
    delete(temp_h);
    temp_h = new double[576*96*1*1];
    for(int i=0;i<576*96*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576*96*1*1, cudaMemcpyHostToDevice);
    Conv_73_W = temp_d;
    delete(temp_h);
    temp_h = new double[576];
    for(int i=0;i<576;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576, cudaMemcpyHostToDevice);
    Conv_73_B = temp_d;
    delete(temp_h);
    temp_h = new double[576*1*3*3];
    for(int i=0;i<576*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576*1*3*3, cudaMemcpyHostToDevice);
    Conv_75_W = temp_d;
    delete(temp_h);
    temp_h = new double[576];
    for(int i=0;i<576;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*576, cudaMemcpyHostToDevice);
    Conv_75_B = temp_d;
    delete(temp_h);
    temp_h = new double[160*576*1*1];
    for(int i=0;i<160*576*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*160*576*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*160*576*1*1, cudaMemcpyHostToDevice);
    Conv_77_W = temp_d;
    delete(temp_h);
    temp_h = new double[160];
    for(int i=0;i<160;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*160);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*160, cudaMemcpyHostToDevice);
    Conv_77_B = temp_d;
    delete(temp_h);
    temp_h = new double[960*160*1*1];
    for(int i=0;i<960*160*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960*160*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960*160*1*1, cudaMemcpyHostToDevice);
    Conv_78_W = temp_d;
    delete(temp_h);
    temp_h = new double[960];
    for(int i=0;i<960;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960, cudaMemcpyHostToDevice);
    Conv_78_B = temp_d;
    delete(temp_h);
    temp_h = new double[960*1*3*3];
    for(int i=0;i<960*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960*1*3*3, cudaMemcpyHostToDevice);
    Conv_80_W = temp_d;
    delete(temp_h);
    temp_h = new double[960];
    for(int i=0;i<960;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960, cudaMemcpyHostToDevice);
    Conv_80_B = temp_d;
    delete(temp_h);
    temp_h = new double[160*960*1*1];
    for(int i=0;i<160*960*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*160*960*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*160*960*1*1, cudaMemcpyHostToDevice);
    Conv_82_W = temp_d;
    delete(temp_h);
    temp_h = new double[160];
    for(int i=0;i<160;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*160);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*160, cudaMemcpyHostToDevice);
    Conv_82_B = temp_d;
    delete(temp_h);
    temp_h = new double[960*160*1*1];
    for(int i=0;i<960*160*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960*160*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960*160*1*1, cudaMemcpyHostToDevice);
    Conv_84_W = temp_d;
    delete(temp_h);
    temp_h = new double[960];
    for(int i=0;i<960;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960, cudaMemcpyHostToDevice);
    Conv_84_B = temp_d;
    delete(temp_h);
    temp_h = new double[960*1*3*3];
    for(int i=0;i<960*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960*1*3*3, cudaMemcpyHostToDevice);
    Conv_86_W = temp_d;
    delete(temp_h);
    temp_h = new double[960];
    for(int i=0;i<960;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960, cudaMemcpyHostToDevice);
    Conv_86_B = temp_d;
    delete(temp_h);
    temp_h = new double[160*960*1*1];
    for(int i=0;i<160*960*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*160*960*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*160*960*1*1, cudaMemcpyHostToDevice);
    Conv_88_W = temp_d;
    delete(temp_h);
    temp_h = new double[160];
    for(int i=0;i<160;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*160);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*160, cudaMemcpyHostToDevice);
    Conv_88_B = temp_d;
    delete(temp_h);
    temp_h = new double[960*160*1*1];
    for(int i=0;i<960*160*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960*160*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960*160*1*1, cudaMemcpyHostToDevice);
    Conv_90_W = temp_d;
    delete(temp_h);
    temp_h = new double[960];
    for(int i=0;i<960;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960, cudaMemcpyHostToDevice);
    Conv_90_B = temp_d;
    delete(temp_h);
    temp_h = new double[960*1*3*3];
    for(int i=0;i<960*1*3*3;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960*1*3*3, cudaMemcpyHostToDevice);
    Conv_92_W = temp_d;
    delete(temp_h);
    temp_h = new double[960];
    for(int i=0;i<960;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*960, cudaMemcpyHostToDevice);
    Conv_92_B = temp_d;
    delete(temp_h);
    temp_h = new double[320*960*1*1];
    for(int i=0;i<320*960*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*320*960*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*320*960*1*1, cudaMemcpyHostToDevice);
    Conv_94_W = temp_d;
    delete(temp_h);
    temp_h = new double[320];
    for(int i=0;i<320;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*320);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*320, cudaMemcpyHostToDevice);
    Conv_94_B = temp_d;
    delete(temp_h);
    temp_h = new double[1280*320*1*1];
    for(int i=0;i<1280*320*1*1;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*1280*320*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*1280*320*1*1, cudaMemcpyHostToDevice);
    Conv_95_W = temp_d;
    delete(temp_h);
    temp_h = new double[1280];
    for(int i=0;i<1280;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*1280);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*1280, cudaMemcpyHostToDevice);
    Conv_95_B = temp_d;
    delete(temp_h);


    double _;
    fscanf(fp,"%lf %lf",&_, &_); // const 1 -1

    temp_h = new double[1280*1000];
    for(int i=0;i<1280*1000;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*1280*1000);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*1280*1000, cudaMemcpyHostToDevice);
    Gemm_W = temp_d;
    delete(temp_h);
    temp_h = new double[1000];
    for(int i=0;i<1000;i++)fscanf(fp,"%lf",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(double)*1000);
    cudaMemcpy(temp_d, temp_h, sizeof(double)*1000, cudaMemcpyHostToDevice);
    Gemm_B = temp_d;
    delete(temp_h);

    cudaMallocWithPadding(&Conv_0_out,32,122,1);
    cudaMallocWithPadding(&Conv_2_out,32,122,1);
    cudaMallocWithPadding(&Conv_4_out,16,122);
    cudaMallocWithPadding(&Conv_5_out,96,122);
    cudaMallocWithPadding(&Conv_7_out,96,61,1);
    cudaMallocWithPadding(&Conv_9_out,24,61);
    cudaMallocWithPadding(&Conv_10_out,144,61);
    cudaMallocWithPadding(&Conv_12_out,144,61,1);
    cudaMallocWithPadding(&Conv_14_out,24,61);
    cudaMallocWithPadding(&Conv_16_out,144,61);
    cudaMallocWithPadding(&Conv_18_out,144,31,1);
    cudaMallocWithPadding(&Conv_20_out,32,31);
    cudaMallocWithPadding(&Conv_21_out,192,31);
    cudaMallocWithPadding(&Conv_23_out,192,31,1);
    cudaMallocWithPadding(&Conv_25_out,32,31);
    cudaMallocWithPadding(&Conv_27_out,192,31);
    cudaMallocWithPadding(&Conv_29_out,192,31,1);
    cudaMallocWithPadding(&Conv_31_out,32,31);
    cudaMallocWithPadding(&Conv_33_out,192,31);
    cudaMallocWithPadding(&Conv_35_out,192,16,1);
    cudaMallocWithPadding(&Conv_37_out,64,16);
    cudaMallocWithPadding(&Conv_38_out,384,16);
    cudaMallocWithPadding(&Conv_40_out,384,16,1);
    cudaMallocWithPadding(&Conv_42_out,64,16);
    cudaMallocWithPadding(&Conv_44_out,384,16);
    cudaMallocWithPadding(&Conv_46_out,384,16,1);
    cudaMallocWithPadding(&Conv_48_out,64,16);
    cudaMallocWithPadding(&Conv_50_out,384,16);
    cudaMallocWithPadding(&Conv_52_out,384,16,1);
    cudaMallocWithPadding(&Conv_54_out,64,16);
    cudaMallocWithPadding(&Conv_56_out,384,16);
    cudaMallocWithPadding(&Conv_58_out,384,16,1);
    cudaMallocWithPadding(&Conv_60_out,96,16);
    cudaMallocWithPadding(&Conv_61_out,576,16);
    cudaMallocWithPadding(&Conv_63_out,576,16,1);
    cudaMallocWithPadding(&Conv_65_out,96,16);
    cudaMallocWithPadding(&Conv_67_out,576,16);
    cudaMallocWithPadding(&Conv_69_out,576,16,1);
    cudaMallocWithPadding(&Conv_71_out,96,16);
    cudaMallocWithPadding(&Conv_73_out,576,16);
    cudaMallocWithPadding(&Conv_75_out,576,8,1);
    cudaMallocWithPadding(&Conv_77_out,160,8);
    cudaMallocWithPadding(&Conv_78_out,960,8);
    cudaMallocWithPadding(&Conv_80_out,960,8,1);
    cudaMallocWithPadding(&Conv_82_out,160,8);
    cudaMallocWithPadding(&Conv_84_out,960,8);
    cudaMallocWithPadding(&Conv_86_out,960,8,1);
    cudaMallocWithPadding(&Conv_88_out,160,8);
    cudaMallocWithPadding(&Conv_90_out,960,8);
    cudaMallocWithPadding(&Conv_92_out,960,8,1);
    cudaMallocWithPadding(&Conv_94_out,320,8);
    cudaMallocWithPadding(&Conv_95_out,1280,8);
    cudaMalloc(&Avgpool_out,sizeof(double)*1280);
    cudaMalloc(&Gemm_out,sizeof(double)*1000);
}

// TODO: 实现自己的inference
void inference(double *input, double *output)
{
    if(DEBUG) printf("========== main::begin inference ==========\n");
    double * image_g =NULL;
    double test_output[10];
    image_g = pad(3,244,1,input);
    conv(3,244,32,122,3,1,2,1,Conv_0_W,Conv_0_B,image_g,Conv_0_out,1);
    conv_group(32,122,32,122,3,1,1,1,Conv_2_W,Conv_2_B,image_g,Conv_2_out,0);
    conv(32,122,16,122,1,0,1,1,Conv_4_W,Conv_4_B,image_g,Conv_4_out,0,false);
    conv(16,122,96,122,1,0,1,1,Conv_5_W,Conv_5_B,image_g,Conv_5_out,1);
    conv_group(96,122,96,61,3,1,2,1,Conv_7_W,Conv_7_B,image_g,Conv_7_out,0);
    conv(96,61,24,61,1,0,1,1,Conv_9_W,Conv_9_B,image_g,Conv_9_out,0,false);
    double* residual_g = imgcpy(image_g, 1*24*61*61);
    conv(24,61,144,61,1,0,1,1,Conv_10_W,Conv_10_B,image_g,Conv_10_out,1);
    conv_group(144,61,144,61,3,1,1,1,Conv_12_W,Conv_12_B,image_g,Conv_12_out,0);
    conv(144,61,24,61,1,0,1,1,Conv_14_W,Conv_14_B,image_g,Conv_14_out,0,false);
    add(24,61,image_g,residual_g);
    conv(24,61,144,61,1,0,1,1,Conv_16_W,Conv_16_B,image_g,Conv_16_out,1);
    conv_group(144,61,144,31,3,1,2,1,Conv_18_W,Conv_18_B,image_g,Conv_18_out,0);
    conv(144,31,32,31,1,0,1,1,Conv_20_W,Conv_20_B,image_g,Conv_20_out,0,false);
    residual_g = imgcpy(image_g,32*31*31);
    conv(32,31,192,31,1,0,1,1,Conv_21_W,Conv_21_B,image_g,Conv_21_out,1);
    conv_group(192,31,192,31,3,1,1,1,Conv_23_W,Conv_23_B,image_g,Conv_23_out,0);
    conv(192,31,32,31,1,0,1,1,Conv_25_W,Conv_25_B,image_g,Conv_25_out,0,false);
    add(32,31,image_g,residual_g);
    residual_g = imgcpy(image_g,32*31*31);
    conv(32,31,192,31,1,0,1,1,Conv_27_W,Conv_27_B,image_g,Conv_27_out,1);
    conv_group(192,31,192,31,3,1,1,1,Conv_29_W,Conv_29_B,image_g,Conv_29_out,0);
    conv(192,31,32,31,1,0,1,1,Conv_31_W,Conv_31_B,image_g,Conv_31_out,0,false);
    add(32,31,image_g,residual_g);
    conv(32,31,192,31,1,0,1,1,Conv_33_W,Conv_33_B,image_g,Conv_33_out,1);
    conv_group(192,31,192,16,3,1,2,1,Conv_35_W,Conv_35_B,image_g,Conv_35_out,0);
    conv(192,16,64,16,1,0,1,1,Conv_37_W,Conv_37_B,image_g,Conv_37_out,0,false);
    residual_g = imgcpy(image_g,64*16*16);
    conv(64,16,384,16,1,0,1,1,Conv_38_W,Conv_38_B,image_g,Conv_38_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_40_W,Conv_40_B,image_g,Conv_40_out,0);
    conv(384,16,64,16,1,0,1,1,Conv_42_W,Conv_42_B,image_g,Conv_42_out,0,false);
    add(64,16,image_g,residual_g);
    residual_g = imgcpy(image_g,64*16*16);
    conv(64,16,384,16,1,0,1,1,Conv_44_W,Conv_44_B,image_g,Conv_44_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_46_W,Conv_46_B,image_g,Conv_46_out,0);
    conv(384,16,64,16,1,0,1,1,Conv_48_W,Conv_48_B,image_g,Conv_48_out,0,false);
    add(64,16,image_g,residual_g);
    residual_g = imgcpy(image_g,64*16*16);
    conv(64,16,384,16,1,0,1,1,Conv_50_W,Conv_50_B,image_g,Conv_50_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_52_W,Conv_52_B,image_g,Conv_52_out,0);
    conv(384,16,64,16,1,0,1,1,Conv_54_W,Conv_54_B,image_g,Conv_54_out,0,false);
    add(64,16,image_g,residual_g);
    conv(64,16,384,16,1,0,1,1,Conv_56_W,Conv_56_B,image_g,Conv_56_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_58_W,Conv_58_B,image_g,Conv_58_out,0);
    conv(384,16,96,16,1,0,1,1,Conv_60_W,Conv_60_B,image_g,Conv_60_out,0,false);
    residual_g = imgcpy(image_g,96*16*16);
    conv(96,16,576,16,1,0,1,1,Conv_61_W,Conv_61_B,image_g,Conv_61_out,1);
    conv_group(576,16,576,16,3,1,1,1,Conv_63_W,Conv_63_B,image_g,Conv_63_out,0);
    conv(576,16,96,16,1,0,1,1,Conv_65_W,Conv_65_B,image_g,Conv_65_out,0,false);
    add(96,16,image_g,residual_g);
    residual_g = imgcpy(image_g,96*16*16);
    conv(96,16,576,16,1,0,1,1,Conv_67_W,Conv_67_B,image_g,Conv_67_out,1);
    conv_group(576,16,576,16,3,1,1,1,Conv_69_W,Conv_69_B,image_g,Conv_69_out,0);
    conv(576,16,96,16,1,0,1,1,Conv_71_W,Conv_71_B,image_g,Conv_71_out,0,false);
    add(96,16,image_g,residual_g);
    conv(96,16,576,16,1,0,1,1,Conv_73_W,Conv_73_B,image_g,Conv_73_out,1);
    conv_group(576,16,576,8,3,1,2,1,Conv_75_W,Conv_75_B,image_g,Conv_75_out,0);
    conv(576,8,160,8,1,0,1,1,Conv_77_W,Conv_77_B,image_g,Conv_77_out,0,false);
    residual_g = imgcpy(image_g,160*8*8);
    conv(160,8,960,8,1,0,1,1,Conv_78_W,Conv_78_B,image_g,Conv_78_out,1);
    conv_group(960,8,960,8,3,1,1,1,Conv_80_W,Conv_80_B,image_g,Conv_80_out,0);
    conv(960,8,160,8,1,0,1,1,Conv_82_W,Conv_82_B,image_g,Conv_82_out,0,false);
    add(160,8,image_g,residual_g);
    residual_g = imgcpy(image_g,160*8*8);
    conv(160,8,960,8,1,0,1,1,Conv_84_W,Conv_84_B,image_g,Conv_84_out,1);
    conv_group(960,8,960,8,3,1,1,1,Conv_86_W,Conv_86_B,image_g,Conv_86_out,0);
    conv(960,8,160,8,1,0,1,1,Conv_88_W,Conv_88_B,image_g,Conv_88_out,0,false);
    add(160,8,image_g,residual_g);
    conv(160,8,960,8,1,0,1,1,Conv_90_W,Conv_90_B,image_g,Conv_90_out,1);
    conv_group(960,8,960,8,3,1,1,1,Conv_92_W,Conv_92_B,image_g,Conv_92_out,0);
    conv(960,8,320,8,1,0,1,1,Conv_94_W,Conv_94_B,image_g,Conv_94_out,0,false);
    conv(320,8,1280,8,1,0,1,1,Conv_95_W,Conv_95_B,image_g,Conv_95_out,0);
    image_g = global_avg(image_g, 1280, 8);
    // conv(1280,1,1000,1,1,0,1,1,Gemm_W,Gemm_B,image_g,Gemm_out,0,false);
    gemm(1000,1280,1280,1,Gemm_W, image_g, Gemm_B, Gemm_out);


    cudaMemcpy(output, Gemm_out, sizeof(double)*1000, cudaMemcpyDeviceToHost);
    // cudaMemcpy(test_output, image_g, sizeof(double)*1*1280*8*8, cudaMemcpyDeviceToHost);
    // for(int i=0;i<1280*8*8;i++){
    //     printf("%lf\n", test_output[i]);
    // }
    if(DEBUG) printf("========== main::end inference ==========\n");
}

int main()
{

    initModel(); // 读取网络权重

    readInput("./mobilenetInput.txt");   // 读取输入
    readOutput("./mobilenetOutput.txt"); // 读取标准输出
    float sumTime = 0;
    for (int i = 0; i < TESTNUM; i++)
    {
        double inferOut[1000];
        for (int j = 0; j < ITERNUM; j++)
        {
            float Onetime;
            cudaEvent_t start, stop;
            cudaEventCreate(&start);
            cudaEventCreate(&stop);
            cudaEventRecord(start, 0);

            // 执行Inference
            inference(inputArr[i], inferOut);

            cudaDeviceSynchronize();
            cudaEventRecord(stop, 0);
            cudaEventSynchronize(stop);
            cudaEventElapsedTime(&Onetime, start, stop);
            // 累加单次推理消耗时间
            sumTime += Onetime;
        }
        checkOutput(benchOutArr[i], inferOut);
    }
    printf("Average Time is: %lf\n", (sumTime / TESTNUM / ITERNUM));
}