#include "conv_float.cuh"
#include "global_avg_float.cuh"
#include "add_float.cuh"
#include "gemm_float.cuh"

#define INPUTSHAPE 3 * 244 * 244
#define OUTPUTSHAPE 1000
#define TESTNUM 10
#define ITERNUM 10
#define DEBUG false
float inputArr[TESTNUM][INPUTSHAPE];
float benchOutArr[TESTNUM][OUTPUTSHAPE];

float* Conv_0_W;
float* Conv_0_B;
float* Conv_2_W;
float* Conv_2_B;
float* Conv_4_W;
float* Conv_4_B;
float* Conv_5_W;
float* Conv_5_B;
float* Conv_7_W;
float* Conv_7_B;
float* Conv_9_W;
float* Conv_9_B;
float* Conv_10_W;
float* Conv_10_B;
float* Conv_12_W;
float* Conv_12_B;
float* Conv_14_W;
float* Conv_14_B;
float* Conv_16_W;
float* Conv_16_B;
float* Conv_18_W;
float* Conv_18_B;
float* Conv_20_W;
float* Conv_20_B;
float* Conv_21_W;
float* Conv_21_B;
float* Conv_23_W;
float* Conv_23_B;
float* Conv_25_W;
float* Conv_25_B;
float* Conv_27_W;
float* Conv_27_B;
float* Conv_29_W;
float* Conv_29_B;
float* Conv_31_W;
float* Conv_31_B;
float* Conv_33_W;
float* Conv_33_B;
float* Conv_35_W;
float* Conv_35_B;
float* Conv_37_W;
float* Conv_37_B;
float* Conv_38_W;
float* Conv_38_B;
float* Conv_40_W;
float* Conv_40_B;
float* Conv_42_W;
float* Conv_42_B;
float* Conv_44_W;
float* Conv_44_B;
float* Conv_46_W;
float* Conv_46_B;
float* Conv_48_W;
float* Conv_48_B;
float* Conv_50_W;
float* Conv_50_B;
float* Conv_52_W;
float* Conv_52_B;
float* Conv_54_W;
float* Conv_54_B;
float* Conv_56_W;
float* Conv_56_B;
float* Conv_58_W;
float* Conv_58_B;
float* Conv_60_W;
float* Conv_60_B;
float* Conv_61_W;
float* Conv_61_B;
float* Conv_63_W;
float* Conv_63_B;
float* Conv_65_W;
float* Conv_65_B;
float* Conv_67_W;
float* Conv_67_B;
float* Conv_69_W;
float* Conv_69_B;
float* Conv_71_W;
float* Conv_71_B;
float* Conv_73_W;
float* Conv_73_B;
float* Conv_75_W;
float* Conv_75_B;
float* Conv_77_W;
float* Conv_77_B;
float* Conv_78_W;
float* Conv_78_B;
float* Conv_80_W;
float* Conv_80_B;
float* Conv_82_W;
float* Conv_82_B;
float* Conv_84_W;
float* Conv_84_B;
float* Conv_86_W;
float* Conv_86_B;
float* Conv_88_W;
float* Conv_88_B;
float* Conv_90_W;
float* Conv_90_B;
float* Conv_92_W;
float* Conv_92_B;
float* Conv_94_W;
float* Conv_94_B;
float* Conv_95_W;
float* Conv_95_B;
float* Gemm_W;
float* Gemm_B;
float* temp_h;
float* temp_d;

float* Conv_0_out;
float* Conv_2_out;
float* Conv_4_out;
float* Conv_5_out;
float* Conv_7_out;
float* Conv_9_out;
float* Conv_10_out;
float* Conv_12_out;
float* Conv_14_out;
float* Conv_16_out;
float* Conv_18_out;
float* Conv_20_out;
float* Conv_21_out;
float* Conv_23_out;
float* Conv_25_out;
float* Conv_27_out;
float* Conv_29_out;
float* Conv_31_out;
float* Conv_33_out;
float* Conv_35_out;
float* Conv_37_out;
float* Conv_38_out;
float* Conv_40_out;
float* Conv_42_out;
float* Conv_44_out;
float* Conv_46_out;
float* Conv_48_out;
float* Conv_50_out;
float* Conv_52_out;
float* Conv_54_out;
float* Conv_56_out;
float* Conv_58_out;
float* Conv_60_out;
float* Conv_61_out;
float* Conv_63_out;
float* Conv_65_out;
float* Conv_67_out;
float* Conv_69_out;
float* Conv_71_out;
float* Conv_73_out;
float* Conv_75_out;
float* Conv_77_out;
float* Conv_78_out;
float* Conv_80_out;
float* Conv_82_out;
float* Conv_84_out;
float* Conv_86_out;
float* Conv_88_out;
float* Conv_90_out;
float* Conv_92_out;
float* Conv_94_out;
float* Conv_95_out;
float* Avgpool_out;
float* Gemm_out;

void readInput(char *filename)
{
    FILE *fp = NULL;
    fp = fopen(filename, "r");
    for (int i = 0; i < TESTNUM; i++)
        for (int j = 0; j < INPUTSHAPE; j++)
            fscanf(fp, "%f", &inputArr[i][j]);
}

void readOutput(char *filename)
{
    FILE *fp = NULL;
    fp = fopen(filename, "r");
    for (int i = 0; i < TESTNUM; i++)
        for (int j = 0; j < OUTPUTSHAPE; j++)
            fscanf(fp, "%f", &benchOutArr[i][j]);
}

void checkOutput(float *out1, float *out2)
{
    float maxDiff = 0;
    for (int i = 0; i < OUTPUTSHAPE; i++)
    {
        maxDiff = (fabs(out1[i] - out2[i]) > maxDiff) ? fabs(out1[i] - out2[i]) : maxDiff;
    }
    if (maxDiff > 1e-5)
    {
        printf("Output dismatch. MaxDiff is %.7f\n", maxDiff);
    }
}

float* imgcpy(const float* image_g, int size)
{
    float* residual_g = NULL;
    cudaMalloc((void**)&residual_g,sizeof(float)*size);
    cudaMemcpy(residual_g, image_g, sizeof(float)*size, cudaMemcpyDeviceToDevice);
    return residual_g;
}

void cudaMallocWithPadding(float** img_p, int channel, int shape, int padding=0)
{
    shape+=padding;
    cudaMalloc(img_p, sizeof(float)*channel*shape*shape*2);
}

void initModel()
{
    FILE *fp = NULL;
    fp = fopen("./params.txt", "r");
    temp_h = new float[32*3*3*3];
    for(int i=0;i<32*3*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32*3*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32*3*3*3, cudaMemcpyHostToDevice);
    Conv_0_W = temp_d;
    delete [] temp_h;
    temp_h = new float[32];
    for(int i=0;i<32;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32, cudaMemcpyHostToDevice);
    Conv_0_B = temp_d;
    delete(temp_h);
    temp_h = new float[32*1*3*3];
    for(int i=0;i<32*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32*1*3*3, cudaMemcpyHostToDevice);
    Conv_2_W = temp_d;
    delete(temp_h);
    temp_h = new float[32];
    for(int i=0;i<32;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32, cudaMemcpyHostToDevice);
    Conv_2_B = temp_d;
    delete(temp_h);
    temp_h = new float[16*32*1*1];
    for(int i=0;i<16*32*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*16*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*16*32*1*1, cudaMemcpyHostToDevice);
    Conv_4_W = temp_d;
    delete(temp_h);
    temp_h = new float[16];
    for(int i=0;i<16;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*16);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*16, cudaMemcpyHostToDevice);
    Conv_4_B = temp_d;
    delete(temp_h);
    temp_h = new float[96*16*1*1];
    for(int i=0;i<96*16*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96*16*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96*16*1*1, cudaMemcpyHostToDevice);
    Conv_5_W = temp_d;
    delete(temp_h);
    temp_h = new float[96];
    for(int i=0;i<96;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96, cudaMemcpyHostToDevice);
    Conv_5_B = temp_d;
    delete(temp_h);
    temp_h = new float[96*1*3*3];
    for(int i=0;i<96*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96*1*3*3, cudaMemcpyHostToDevice);
    Conv_7_W = temp_d;
    delete(temp_h);
    temp_h = new float[96];
    for(int i=0;i<96;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96, cudaMemcpyHostToDevice);
    Conv_7_B = temp_d;
    delete(temp_h);
    temp_h = new float[24*96*1*1];
    for(int i=0;i<24*96*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*24*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*24*96*1*1, cudaMemcpyHostToDevice);
    Conv_9_W = temp_d;
    delete(temp_h);
    temp_h = new float[24];
    for(int i=0;i<24;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*24);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*24, cudaMemcpyHostToDevice);
    Conv_9_B = temp_d;
    delete(temp_h);
    temp_h = new float[144*24*1*1];
    for(int i=0;i<144*24*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144*24*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144*24*1*1, cudaMemcpyHostToDevice);
    Conv_10_W = temp_d;
    delete(temp_h);
    temp_h = new float[144];
    for(int i=0;i<144;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144, cudaMemcpyHostToDevice);
    Conv_10_B = temp_d;
    delete(temp_h);
    temp_h = new float[144*1*3*3];
    for(int i=0;i<144*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144*1*3*3, cudaMemcpyHostToDevice);
    Conv_12_W = temp_d;
    delete(temp_h);
    temp_h = new float[144];
    for(int i=0;i<144;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144, cudaMemcpyHostToDevice);
    Conv_12_B = temp_d;
    delete(temp_h);
    temp_h = new float[24*144*1*1];
    for(int i=0;i<24*144*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*24*144*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*24*144*1*1, cudaMemcpyHostToDevice);
    Conv_14_W = temp_d;
    delete(temp_h);
    temp_h = new float[24];
    for(int i=0;i<24;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*24);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*24, cudaMemcpyHostToDevice);
    Conv_14_B = temp_d;
    delete(temp_h);
    temp_h = new float[144*24*1*1];
    for(int i=0;i<144*24*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144*24*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144*24*1*1, cudaMemcpyHostToDevice);
    Conv_16_W = temp_d;
    delete(temp_h);
    temp_h = new float[144];
    for(int i=0;i<144;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144, cudaMemcpyHostToDevice);
    Conv_16_B = temp_d;
    delete(temp_h);
    temp_h = new float[144*1*3*3];
    for(int i=0;i<144*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144*1*3*3, cudaMemcpyHostToDevice);
    Conv_18_W = temp_d;
    delete(temp_h);
    temp_h = new float[144];
    for(int i=0;i<144;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*144);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*144, cudaMemcpyHostToDevice);
    Conv_18_B = temp_d;
    delete(temp_h);
    temp_h = new float[32*144*1*1];
    for(int i=0;i<32*144*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32*144*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32*144*1*1, cudaMemcpyHostToDevice);
    Conv_20_W = temp_d;
    delete(temp_h);
    temp_h = new float[32];
    for(int i=0;i<32;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32, cudaMemcpyHostToDevice);
    Conv_20_B = temp_d;
    delete(temp_h);
    temp_h = new float[192*32*1*1];
    for(int i=0;i<192*32*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192*32*1*1, cudaMemcpyHostToDevice);
    Conv_21_W = temp_d;
    delete(temp_h);
    temp_h = new float[192];
    for(int i=0;i<192;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192, cudaMemcpyHostToDevice);
    Conv_21_B = temp_d;
    delete(temp_h);
    temp_h = new float[192*1*3*3];
    for(int i=0;i<192*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192*1*3*3, cudaMemcpyHostToDevice);
    Conv_23_W = temp_d;
    delete(temp_h);
    temp_h = new float[192];
    for(int i=0;i<192;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192, cudaMemcpyHostToDevice);
    Conv_23_B = temp_d;
    delete(temp_h);
    temp_h = new float[32*192*1*1];
    for(int i=0;i<32*192*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32*192*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32*192*1*1, cudaMemcpyHostToDevice);
    Conv_25_W = temp_d;
    delete(temp_h);
    temp_h = new float[32];
    for(int i=0;i<32;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32, cudaMemcpyHostToDevice);
    Conv_25_B = temp_d;
    delete(temp_h);
    temp_h = new float[192*32*1*1];
    for(int i=0;i<192*32*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192*32*1*1, cudaMemcpyHostToDevice);
    Conv_27_W = temp_d;
    delete(temp_h);
    temp_h = new float[192];
    for(int i=0;i<192;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192, cudaMemcpyHostToDevice);
    Conv_27_B = temp_d;
    delete(temp_h);
    temp_h = new float[192*1*3*3];
    for(int i=0;i<192*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192*1*3*3, cudaMemcpyHostToDevice);
    Conv_29_W = temp_d;
    delete(temp_h);
    temp_h = new float[192];
    for(int i=0;i<192;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192, cudaMemcpyHostToDevice);
    Conv_29_B = temp_d;
    delete(temp_h);
    temp_h = new float[32*192*1*1];
    for(int i=0;i<32*192*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32*192*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32*192*1*1, cudaMemcpyHostToDevice);
    Conv_31_W = temp_d;
    delete(temp_h);
    temp_h = new float[32];
    for(int i=0;i<32;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*32);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*32, cudaMemcpyHostToDevice);
    Conv_31_B = temp_d;
    delete(temp_h);
    temp_h = new float[192*32*1*1];
    for(int i=0;i<192*32*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192*32*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192*32*1*1, cudaMemcpyHostToDevice);
    Conv_33_W = temp_d;
    delete(temp_h);
    temp_h = new float[192];
    for(int i=0;i<192;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192, cudaMemcpyHostToDevice);
    Conv_33_B = temp_d;
    delete(temp_h);
    temp_h = new float[192*1*3*3];
    for(int i=0;i<192*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192*1*3*3, cudaMemcpyHostToDevice);
    Conv_35_W = temp_d;
    delete(temp_h);
    temp_h = new float[192];
    for(int i=0;i<192;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*192);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*192, cudaMemcpyHostToDevice);
    Conv_35_B = temp_d;
    delete(temp_h);
    temp_h = new float[64*192*1*1];
    for(int i=0;i<64*192*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64*192*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64*192*1*1, cudaMemcpyHostToDevice);
    Conv_37_W = temp_d;
    delete(temp_h);
    temp_h = new float[64];
    for(int i=0;i<64;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64, cudaMemcpyHostToDevice);
    Conv_37_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_38_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_38_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_40_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_40_B = temp_d;
    delete(temp_h);
    temp_h = new float[64*384*1*1];
    for(int i=0;i<64*384*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64*384*1*1, cudaMemcpyHostToDevice);
    Conv_42_W = temp_d;
    delete(temp_h);
    temp_h = new float[64];
    for(int i=0;i<64;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64, cudaMemcpyHostToDevice);
    Conv_42_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_44_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_44_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_46_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_46_B = temp_d;
    delete(temp_h);
    temp_h = new float[64*384*1*1];
    for(int i=0;i<64*384*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64*384*1*1, cudaMemcpyHostToDevice);
    Conv_48_W = temp_d;
    delete(temp_h);
    temp_h = new float[64];
    for(int i=0;i<64;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64, cudaMemcpyHostToDevice);
    Conv_48_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_50_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_50_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_52_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_52_B = temp_d;
    delete(temp_h);
    temp_h = new float[64*384*1*1];
    for(int i=0;i<64*384*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64*384*1*1, cudaMemcpyHostToDevice);
    Conv_54_W = temp_d;
    delete(temp_h);
    temp_h = new float[64];
    for(int i=0;i<64;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*64);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*64, cudaMemcpyHostToDevice);
    Conv_54_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*64*1*1];
    for(int i=0;i<384*64*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*64*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*64*1*1, cudaMemcpyHostToDevice);
    Conv_56_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_56_B = temp_d;
    delete(temp_h);
    temp_h = new float[384*1*3*3];
    for(int i=0;i<384*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384*1*3*3, cudaMemcpyHostToDevice);
    Conv_58_W = temp_d;
    delete(temp_h);
    temp_h = new float[384];
    for(int i=0;i<384;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*384);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*384, cudaMemcpyHostToDevice);
    Conv_58_B = temp_d;
    delete(temp_h);
    temp_h = new float[96*384*1*1];
    for(int i=0;i<96*384*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96*384*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96*384*1*1, cudaMemcpyHostToDevice);
    Conv_60_W = temp_d;
    delete(temp_h);
    temp_h = new float[96];
    for(int i=0;i<96;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96, cudaMemcpyHostToDevice);
    Conv_60_B = temp_d;
    delete(temp_h);
    temp_h = new float[576*96*1*1];
    for(int i=0;i<576*96*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576*96*1*1, cudaMemcpyHostToDevice);
    Conv_61_W = temp_d;
    delete(temp_h);
    temp_h = new float[576];
    for(int i=0;i<576;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576, cudaMemcpyHostToDevice);
    Conv_61_B = temp_d;
    delete(temp_h);
    temp_h = new float[576*1*3*3];
    for(int i=0;i<576*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576*1*3*3, cudaMemcpyHostToDevice);
    Conv_63_W = temp_d;
    delete(temp_h);
    temp_h = new float[576];
    for(int i=0;i<576;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576, cudaMemcpyHostToDevice);
    Conv_63_B = temp_d;
    delete(temp_h);
    temp_h = new float[96*576*1*1];
    for(int i=0;i<96*576*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96*576*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96*576*1*1, cudaMemcpyHostToDevice);
    Conv_65_W = temp_d;
    delete(temp_h);
    temp_h = new float[96];
    for(int i=0;i<96;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96, cudaMemcpyHostToDevice);
    Conv_65_B = temp_d;
    delete(temp_h);
    temp_h = new float[576*96*1*1];
    for(int i=0;i<576*96*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576*96*1*1, cudaMemcpyHostToDevice);
    Conv_67_W = temp_d;
    delete(temp_h);
    temp_h = new float[576];
    for(int i=0;i<576;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576, cudaMemcpyHostToDevice);
    Conv_67_B = temp_d;
    delete(temp_h);
    temp_h = new float[576*1*3*3];
    for(int i=0;i<576*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576*1*3*3, cudaMemcpyHostToDevice);
    Conv_69_W = temp_d;
    delete(temp_h);
    temp_h = new float[576];
    for(int i=0;i<576;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576, cudaMemcpyHostToDevice);
    Conv_69_B = temp_d;
    delete(temp_h);
    temp_h = new float[96*576*1*1];
    for(int i=0;i<96*576*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96*576*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96*576*1*1, cudaMemcpyHostToDevice);
    Conv_71_W = temp_d;
    delete(temp_h);
    temp_h = new float[96];
    for(int i=0;i<96;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*96);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*96, cudaMemcpyHostToDevice);
    Conv_71_B = temp_d;
    delete(temp_h);
    temp_h = new float[576*96*1*1];
    for(int i=0;i<576*96*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576*96*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576*96*1*1, cudaMemcpyHostToDevice);
    Conv_73_W = temp_d;
    delete(temp_h);
    temp_h = new float[576];
    for(int i=0;i<576;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576, cudaMemcpyHostToDevice);
    Conv_73_B = temp_d;
    delete(temp_h);
    temp_h = new float[576*1*3*3];
    for(int i=0;i<576*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576*1*3*3, cudaMemcpyHostToDevice);
    Conv_75_W = temp_d;
    delete(temp_h);
    temp_h = new float[576];
    for(int i=0;i<576;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*576);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*576, cudaMemcpyHostToDevice);
    Conv_75_B = temp_d;
    delete(temp_h);
    temp_h = new float[160*576*1*1];
    for(int i=0;i<160*576*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*160*576*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*160*576*1*1, cudaMemcpyHostToDevice);
    Conv_77_W = temp_d;
    delete(temp_h);
    temp_h = new float[160];
    for(int i=0;i<160;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*160);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*160, cudaMemcpyHostToDevice);
    Conv_77_B = temp_d;
    delete(temp_h);
    temp_h = new float[960*160*1*1];
    for(int i=0;i<960*160*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960*160*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960*160*1*1, cudaMemcpyHostToDevice);
    Conv_78_W = temp_d;
    delete(temp_h);
    temp_h = new float[960];
    for(int i=0;i<960;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960, cudaMemcpyHostToDevice);
    Conv_78_B = temp_d;
    delete(temp_h);
    temp_h = new float[960*1*3*3];
    for(int i=0;i<960*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960*1*3*3, cudaMemcpyHostToDevice);
    Conv_80_W = temp_d;
    delete(temp_h);
    temp_h = new float[960];
    for(int i=0;i<960;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960, cudaMemcpyHostToDevice);
    Conv_80_B = temp_d;
    delete(temp_h);
    temp_h = new float[160*960*1*1];
    for(int i=0;i<160*960*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*160*960*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*160*960*1*1, cudaMemcpyHostToDevice);
    Conv_82_W = temp_d;
    delete(temp_h);
    temp_h = new float[160];
    for(int i=0;i<160;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*160);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*160, cudaMemcpyHostToDevice);
    Conv_82_B = temp_d;
    delete(temp_h);
    temp_h = new float[960*160*1*1];
    for(int i=0;i<960*160*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960*160*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960*160*1*1, cudaMemcpyHostToDevice);
    Conv_84_W = temp_d;
    delete(temp_h);
    temp_h = new float[960];
    for(int i=0;i<960;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960, cudaMemcpyHostToDevice);
    Conv_84_B = temp_d;
    delete(temp_h);
    temp_h = new float[960*1*3*3];
    for(int i=0;i<960*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960*1*3*3, cudaMemcpyHostToDevice);
    Conv_86_W = temp_d;
    delete(temp_h);
    temp_h = new float[960];
    for(int i=0;i<960;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960, cudaMemcpyHostToDevice);
    Conv_86_B = temp_d;
    delete(temp_h);
    temp_h = new float[160*960*1*1];
    for(int i=0;i<160*960*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*160*960*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*160*960*1*1, cudaMemcpyHostToDevice);
    Conv_88_W = temp_d;
    delete(temp_h);
    temp_h = new float[160];
    for(int i=0;i<160;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*160);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*160, cudaMemcpyHostToDevice);
    Conv_88_B = temp_d;
    delete(temp_h);
    temp_h = new float[960*160*1*1];
    for(int i=0;i<960*160*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960*160*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960*160*1*1, cudaMemcpyHostToDevice);
    Conv_90_W = temp_d;
    delete(temp_h);
    temp_h = new float[960];
    for(int i=0;i<960;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960, cudaMemcpyHostToDevice);
    Conv_90_B = temp_d;
    delete(temp_h);
    temp_h = new float[960*1*3*3];
    for(int i=0;i<960*1*3*3;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960*1*3*3);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960*1*3*3, cudaMemcpyHostToDevice);
    Conv_92_W = temp_d;
    delete(temp_h);
    temp_h = new float[960];
    for(int i=0;i<960;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*960);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*960, cudaMemcpyHostToDevice);
    Conv_92_B = temp_d;
    delete(temp_h);
    temp_h = new float[320*960*1*1];
    for(int i=0;i<320*960*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*320*960*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*320*960*1*1, cudaMemcpyHostToDevice);
    Conv_94_W = temp_d;
    delete(temp_h);
    temp_h = new float[320];
    for(int i=0;i<320;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*320);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*320, cudaMemcpyHostToDevice);
    Conv_94_B = temp_d;
    delete(temp_h);
    temp_h = new float[1280*320*1*1];
    for(int i=0;i<1280*320*1*1;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*1280*320*1*1);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*1280*320*1*1, cudaMemcpyHostToDevice);
    Conv_95_W = temp_d;
    delete(temp_h);
    temp_h = new float[1280];
    for(int i=0;i<1280;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*1280);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*1280, cudaMemcpyHostToDevice);
    Conv_95_B = temp_d;
    delete(temp_h);


    float _;
    fscanf(fp,"%f %f",&_, &_); // const 1 -1

    temp_h = new float[1280*1000];
    for(int i=0;i<1280*1000;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*1280*1000);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*1280*1000, cudaMemcpyHostToDevice);
    Gemm_W = temp_d;
    delete(temp_h);
    temp_h = new float[1000];
    for(int i=0;i<1000;i++)fscanf(fp,"%f",&temp_h[i]);
    cudaMalloc((void**)&temp_d, sizeof(float)*1000);
    cudaMemcpy(temp_d, temp_h, sizeof(float)*1000, cudaMemcpyHostToDevice);
    Gemm_B = temp_d;
    delete(temp_h);

    cudaMallocWithPadding(&Conv_0_out,32,122,1);
    cudaMallocWithPadding(&Conv_2_out,32,122,1);
    cudaMallocWithPadding(&Conv_4_out,16,122);
    cudaMallocWithPadding(&Conv_5_out,96,122);
    cudaMallocWithPadding(&Conv_7_out,96,61,1);
    cudaMallocWithPadding(&Conv_9_out,24,61);
    cudaMallocWithPadding(&Conv_10_out,144,61);
    cudaMallocWithPadding(&Conv_12_out,144,61,1);
    cudaMallocWithPadding(&Conv_14_out,24,61);
    cudaMallocWithPadding(&Conv_16_out,144,61);
    cudaMallocWithPadding(&Conv_18_out,144,31,1);
    cudaMallocWithPadding(&Conv_20_out,32,31);
    cudaMallocWithPadding(&Conv_21_out,192,31);
    cudaMallocWithPadding(&Conv_23_out,192,31,1);
    cudaMallocWithPadding(&Conv_25_out,32,31);
    cudaMallocWithPadding(&Conv_27_out,192,31);
    cudaMallocWithPadding(&Conv_29_out,192,31,1);
    cudaMallocWithPadding(&Conv_31_out,32,31);
    cudaMallocWithPadding(&Conv_33_out,192,31);
    cudaMallocWithPadding(&Conv_35_out,192,16,1);
    cudaMallocWithPadding(&Conv_37_out,64,16);
    cudaMallocWithPadding(&Conv_38_out,384,16);
    cudaMallocWithPadding(&Conv_40_out,384,16,1);
    cudaMallocWithPadding(&Conv_42_out,64,16);
    cudaMallocWithPadding(&Conv_44_out,384,16);
    cudaMallocWithPadding(&Conv_46_out,384,16,1);
    cudaMallocWithPadding(&Conv_48_out,64,16);
    cudaMallocWithPadding(&Conv_50_out,384,16);
    cudaMallocWithPadding(&Conv_52_out,384,16,1);
    cudaMallocWithPadding(&Conv_54_out,64,16);
    cudaMallocWithPadding(&Conv_56_out,384,16);
    cudaMallocWithPadding(&Conv_58_out,384,16,1);
    cudaMallocWithPadding(&Conv_60_out,96,16);
    cudaMallocWithPadding(&Conv_61_out,576,16);
    cudaMallocWithPadding(&Conv_63_out,576,16,1);
    cudaMallocWithPadding(&Conv_65_out,96,16);
    cudaMallocWithPadding(&Conv_67_out,576,16);
    cudaMallocWithPadding(&Conv_69_out,576,16,1);
    cudaMallocWithPadding(&Conv_71_out,96,16);
    cudaMallocWithPadding(&Conv_73_out,576,16);
    cudaMallocWithPadding(&Conv_75_out,576,8,1);
    cudaMallocWithPadding(&Conv_77_out,160,8);
    cudaMallocWithPadding(&Conv_78_out,960,8);
    cudaMallocWithPadding(&Conv_80_out,960,8,1);
    cudaMallocWithPadding(&Conv_82_out,160,8);
    cudaMallocWithPadding(&Conv_84_out,960,8);
    cudaMallocWithPadding(&Conv_86_out,960,8,1);
    cudaMallocWithPadding(&Conv_88_out,160,8);
    cudaMallocWithPadding(&Conv_90_out,960,8);
    cudaMallocWithPadding(&Conv_92_out,960,8,1);
    cudaMallocWithPadding(&Conv_94_out,320,8);
    cudaMallocWithPadding(&Conv_95_out,1280,8);
    cudaMalloc(&Avgpool_out,sizeof(float)*1280);
    cudaMalloc(&Gemm_out,sizeof(float)*1000);
}

// TODO: 实现自己的inference
void inference(float *input, float *output)
{
    if(DEBUG) printf("========== main::begin inference ==========\n");
    float * image_g =NULL;
    float test_output[10];
    // cudaMalloc((void**)&image_g, sizeof(float)*1*3*244*244);
    // cudaMemcpy(image_g, input, sizeof(float)*1*3*244*244, cudaMemcpyHostToDevice);
    image_g = pad(3,244,1,input);
    conv(3,244,32,122,3,1,2,1,Conv_0_W,Conv_0_B,image_g,Conv_0_out,1);
    conv_group(32,122,32,122,3,1,1,1,Conv_2_W,Conv_2_B,image_g,Conv_2_out,0);
    conv(32,122,16,122,1,0,1,1,Conv_4_W,Conv_4_B,image_g,Conv_4_out,0,false);
    conv(16,122,96,122,1,0,1,1,Conv_5_W,Conv_5_B,image_g,Conv_5_out,1);
    conv_group(96,122,96,61,3,1,2,1,Conv_7_W,Conv_7_B,image_g,Conv_7_out,0);
    conv(96,61,24,61,1,0,1,1,Conv_9_W,Conv_9_B,image_g,Conv_9_out,0,false);
    float* residual_g = imgcpy(image_g, 1*24*61*61);
    conv(24,61,144,61,1,0,1,1,Conv_10_W,Conv_10_B,image_g,Conv_10_out,1);
    conv_group(144,61,144,61,3,1,1,1,Conv_12_W,Conv_12_B,image_g,Conv_12_out,0);
    conv(144,61,24,61,1,0,1,1,Conv_14_W,Conv_14_B,image_g,Conv_14_out,0,false);
    add(24,61,image_g,residual_g);
    conv(24,61,144,61,1,0,1,1,Conv_16_W,Conv_16_B,image_g,Conv_16_out,1);
    conv_group(144,61,144,31,3,1,2,1,Conv_18_W,Conv_18_B,image_g,Conv_18_out,0);
    conv(144,31,32,31,1,0,1,1,Conv_20_W,Conv_20_B,image_g,Conv_20_out,0,false);
    residual_g = imgcpy(image_g,32*31*31);
    conv(32,31,192,31,1,0,1,1,Conv_21_W,Conv_21_B,image_g,Conv_21_out,1);
    conv_group(192,31,192,31,3,1,1,1,Conv_23_W,Conv_23_B,image_g,Conv_23_out,0);
    conv(192,31,32,31,1,0,1,1,Conv_25_W,Conv_25_B,image_g,Conv_25_out,0,false);
    add(32,31,image_g,residual_g);
    residual_g = imgcpy(image_g,32*31*31);
    conv(32,31,192,31,1,0,1,1,Conv_27_W,Conv_27_B,image_g,Conv_27_out,1);
    conv_group(192,31,192,31,3,1,1,1,Conv_29_W,Conv_29_B,image_g,Conv_29_out,0);
    conv(192,31,32,31,1,0,1,1,Conv_31_W,Conv_31_B,image_g,Conv_31_out,0,false);
    add(32,31,image_g,residual_g);
    conv(32,31,192,31,1,0,1,1,Conv_33_W,Conv_33_B,image_g,Conv_33_out,1);
    conv_group(192,31,192,16,3,1,2,1,Conv_35_W,Conv_35_B,image_g,Conv_35_out,0);
    conv(192,16,64,16,1,0,1,1,Conv_37_W,Conv_37_B,image_g,Conv_37_out,0,false);
    residual_g = imgcpy(image_g,64*16*16);
    conv(64,16,384,16,1,0,1,1,Conv_38_W,Conv_38_B,image_g,Conv_38_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_40_W,Conv_40_B,image_g,Conv_40_out,0);
    conv(384,16,64,16,1,0,1,1,Conv_42_W,Conv_42_B,image_g,Conv_42_out,0,false);
    add(64,16,image_g,residual_g);
    residual_g = imgcpy(image_g,64*16*16);
    conv(64,16,384,16,1,0,1,1,Conv_44_W,Conv_44_B,image_g,Conv_44_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_46_W,Conv_46_B,image_g,Conv_46_out,0);
    conv(384,16,64,16,1,0,1,1,Conv_48_W,Conv_48_B,image_g,Conv_48_out,0,false);
    add(64,16,image_g,residual_g);
    residual_g = imgcpy(image_g,64*16*16);
    conv(64,16,384,16,1,0,1,1,Conv_50_W,Conv_50_B,image_g,Conv_50_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_52_W,Conv_52_B,image_g,Conv_52_out,0);
    conv(384,16,64,16,1,0,1,1,Conv_54_W,Conv_54_B,image_g,Conv_54_out,0,false);
    add(64,16,image_g,residual_g);
    conv(64,16,384,16,1,0,1,1,Conv_56_W,Conv_56_B,image_g,Conv_56_out,1);
    conv_group(384,16,384,16,3,1,1,1,Conv_58_W,Conv_58_B,image_g,Conv_58_out,0);
    conv(384,16,96,16,1,0,1,1,Conv_60_W,Conv_60_B,image_g,Conv_60_out,0,false);
    residual_g = imgcpy(image_g,96*16*16);
    conv(96,16,576,16,1,0,1,1,Conv_61_W,Conv_61_B,image_g,Conv_61_out,1);
    conv_group(576,16,576,16,3,1,1,1,Conv_63_W,Conv_63_B,image_g,Conv_63_out,0);
    conv(576,16,96,16,1,0,1,1,Conv_65_W,Conv_65_B,image_g,Conv_65_out,0,false);
    add(96,16,image_g,residual_g);
    residual_g = imgcpy(image_g,96*16*16);
    conv(96,16,576,16,1,0,1,1,Conv_67_W,Conv_67_B,image_g,Conv_67_out,1);
    conv_group(576,16,576,16,3,1,1,1,Conv_69_W,Conv_69_B,image_g,Conv_69_out,0);
    conv(576,16,96,16,1,0,1,1,Conv_71_W,Conv_71_B,image_g,Conv_71_out,0,false);
    add(96,16,image_g,residual_g);
    conv(96,16,576,16,1,0,1,1,Conv_73_W,Conv_73_B,image_g,Conv_73_out,1);
    conv_group(576,16,576,8,3,1,2,1,Conv_75_W,Conv_75_B,image_g,Conv_75_out,0);
    conv(576,8,160,8,1,0,1,1,Conv_77_W,Conv_77_B,image_g,Conv_77_out,0,false);
    residual_g = imgcpy(image_g,160*8*8);
    conv(160,8,960,8,1,0,1,1,Conv_78_W,Conv_78_B,image_g,Conv_78_out,1);
    conv_group(960,8,960,8,3,1,1,1,Conv_80_W,Conv_80_B,image_g,Conv_80_out,0);
    conv(960,8,160,8,1,0,1,1,Conv_82_W,Conv_82_B,image_g,Conv_82_out,0,false);
    add(160,8,image_g,residual_g);
    residual_g = imgcpy(image_g,160*8*8);
    conv(160,8,960,8,1,0,1,1,Conv_84_W,Conv_84_B,image_g,Conv_84_out,1);
    conv_group(960,8,960,8,3,1,1,1,Conv_86_W,Conv_86_B,image_g,Conv_86_out,0);
    conv(960,8,160,8,1,0,1,1,Conv_88_W,Conv_88_B,image_g,Conv_88_out,0,false);
    add(160,8,image_g,residual_g);
    conv(160,8,960,8,1,0,1,1,Conv_90_W,Conv_90_B,image_g,Conv_90_out,1);
    conv_group(960,8,960,8,3,1,1,1,Conv_92_W,Conv_92_B,image_g,Conv_92_out,0);
    conv(960,8,320,8,1,0,1,1,Conv_94_W,Conv_94_B,image_g,Conv_94_out,0,false);
    conv(320,8,1280,8,1,0,1,1,Conv_95_W,Conv_95_B,image_g,Conv_95_out,0);
    image_g = global_avg(image_g, 1280, 8);
    conv(1280,1,1000,1,1,0,1,1,Gemm_W,Gemm_B,image_g,Gemm_out,0,false);


    cudaMemcpy(output, image_g, sizeof(float)*1000, cudaMemcpyDeviceToHost);
    // cudaMemcpy(test_output, image_g, sizeof(float)*1*1280*8*8, cudaMemcpyDeviceToHost);
    // for(int i=0;i<1280*8*8;i++){
    //     printf("%f\n", test_output[i]);
    // }
    if(DEBUG) printf("========== main::end inference ==========\n");
}

int main()
{

    initModel(); // 读取网络权重

    readInput("./mobilenetInput.txt");   // 读取输入
    readOutput("./mobilenetOutput.txt"); // 读取标准输出
    float sumTime = 0;
    for (int i = 0; i < TESTNUM; i++)
    {
        float inferOut[1000];
        for (int j = 0; j < ITERNUM; j++)
        {
            float Onetime;
            cudaEvent_t start, stop;
            cudaEventCreate(&start);
            cudaEventCreate(&stop);
            cudaEventRecord(start, 0);

            // 执行Inference
            inference(inputArr[i], inferOut);

            cudaDeviceSynchronize();
            cudaEventRecord(stop, 0);
            cudaEventSynchronize(stop);
            cudaEventElapsedTime(&Onetime, start, stop);
            // 累加单次推理消耗时间
            sumTime += Onetime;
        }
        checkOutput(benchOutArr[i], inferOut);
    }
    printf("Average Time is: %f\n", (sumTime / TESTNUM / ITERNUM));
}